version: "3"
services:
  nginx:
    container_name: php74-nginx
    image: nginx
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - .src/:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/crt:/etc/nginx/ssl_key
    networks:
      - php74-network
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php74-php
    volumes:
      - ./src:/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - php74-network
  mysql:
    image: mysql:5.7
    container_name: php74-mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - php74-network
networks:
  php74-network:
